# Generated by Django 5.1.5 on 2025-01-14 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_two_factor_enabled_user_two_factor_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='two_factor_enabled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='two_factor_secret',
        ),
    ]
