# Generated by Django 5.1.5 on 2025-01-15 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_verification_token_expiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordresettoken',
            old_name='token',
            new_name='token_hash',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='verification_token',
            new_name='verification_token_hash',
        ),
    ]
