# Generated by Django 5.1.5 on 2025-01-21 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('medicine', 'Медицина'), ('emergency', 'Неотложная помощь'), ('charity', 'Благотворительность'), ('education', 'Образование'), ('animals', 'Животные'), ('ecology', 'Экология'), ('sports', 'Спорт'), ('general', 'Общий сбор средств')], max_length=50)),
                ('description', models.TextField(max_length=3000)),
                ('images', models.ImageField(blank=True, null=True, upload_to='publications/images/')),
                ('bank_details', models.TextField(max_length=1000)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
