# Generated by Django 5.1.5 on 2025-01-21 12:03

import django.db.models.deletion
import phonenumber_field.modelfields
import publications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_remove_publication_images_publicationimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Сумма, которую необходимо собрать.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='publication',
            name='bank_details',
            field=models.TextField(max_length=1000, validators=[publications.models.validate_bank_details]),
        ),
        migrations.AlterField(
            model_name='publication',
            name='contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='publicationimage',
            name='image',
            field=models.ImageField(upload_to='publications/images/', validators=[publications.models.validate_file_size, publications.models.validate_image_format]),
        ),
        migrations.CreateModel(
            name='PublicationVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='publications/videos/', validators=[publications.models.validate_file_size, publications.models.validate_video_format])),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='publications.publication')),
            ],
        ),
    ]
